# GoReleaser configuration
# https://goreleaser.com

version: 2

project_name: yt-player

before:
  hooks:
    - go mod tidy

builds:
  - id: yt-player
    main: .
    binary: yt-player
    
    env:
      - CGO_ENABLED=0
    
    ldflags:
      - -s -w -X main.version={{.Version}}

    gcflags:
      - -trimpath

    goos:
      - linux
      - windows
      - darwin

    goarch:
      - amd64
      - arm64
      - arm

    ignore:
      - goos: darwin
        goarch: '386'
      - goos: windows
        goarch: arm

    tags:
      - pure


archives:
  - id: default
    name_template: "yt-player_v1.2.1-5-gf4cdaba-dirty_{{.Os}}_{{.Arch}}"
    
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]
    
    files:
      - LICENSE*
      - README*
      - CHANGELOG*
      - config.sample.json

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  version_template: "v1.2.2-next-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: "Katrovsky"
    name: "yt-player-obs-donatty"
  
  draft: false
  prerelease: auto
  mode: append
  
  footer: |
    ## Installation
    Download the appropriate archive for your platform from the assets below.