version: 2
project_name: yt-player

before:
  hooks:
    - go mod tidy

builds:
  # Linux: amd64, arm64, arm (32-bit для роутеров и одноплатников)
  - id: mm-tool-linux
    main: .
    binary: mm-tool
    env:
      - CGO_ENABLED=0
      - GOEXPERIMENT=greenteagc
    ldflags:
      - -s -w
    flags:
      - -trimpath
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 6
      - 7
  # Windows, macOS: только amd64 и arm64 (32-bit arm не поддерживается)
  - id: mm-tool-other
    main: .
    binary: mm-tool
    env:
      - CGO_ENABLED=0
      - GOEXPERIMENT=greenteagc
    ldflags:
      - -s -w
    flags:
      - -trimpath
    goos:
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: yt-player
    ids:
      - yt-player-linux
      - yt-player-other
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}_
      {{ .Version }}_
      {{ title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "arm" }}armv{{ .Arm }}
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - README.md
      - LICENSE*
      - config.sample.json

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - 'typo'

release:
  github:
    owner: Katrovsky
    name: yt-player
  draft: false
  prerelease: auto
  name_template: "{{ .ProjectName }} v{{ .Version }}"