# GoReleaser configuration
# https://goreleaser.com

version: 2

project_name: yt-player

before:
  hooks:
    - go mod tidy

builds:
  - id: yt-player
    main: .
    binary: yt-player

    env:
      - CGO_ENABLED=0

    ldflags:
      - -s -w

    flags:
      - -trimpath

    goos:
      - linux
      - windows
      - darwin

    goarch:
      - amd64
      - arm64
      - arm

    ignore:
      - goos: darwin
        goarch: '386'
      - goos: windows
        goarch: arm

    tags:
      - pure

archives:
  - id: default
    name_template: "yt-player_{{.Version}}_{{.Os}}_{{.Arch}}"

    format_overrides:
      - goos: windows
        formats: [ 'zip' ]

    files:
      - LICENSE*
      - README*
      - CHANGELOG*
      - config.sample.json

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  groups:
    - title: "New Features"
      regexp: '^feat(\(.+\))?:'
      order: 0
    - title: "Bug Fixes"
      regexp: '^fix(\(.+\))?:'
      order: 1
    - title: "UI"
      regexp: '^ui(\(.+\))?:'
      order: 2
    - title: "Refactoring"
      regexp: '^refactor(\(.+\))?:'
      order: 3
    - title: "Build & CI"
      regexp: '^(build|ci)(\(.+\))?:'
      order: 4
    - title: "Other"
      order: 99
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: "Katrovsky"
    name: "yt-player-obs-donatty"

  draft: false
  prerelease: auto
  mode: replace

  header: |
    ## yt-player {{ .Tag }}

  footer: |
    ---
    ## Installation
    Download the archive for your platform below, extract, and run `yt-player` alongside OBS.